### ISSUE TITLE
Universal volume control on Android app

### ISSUE THREAD

**Issue by emlopes** [Ciock/rolify#8]
It would be very useful to have a universal volume control so I could keep the same mix but reduce the volume globally.

Of course I could use the android system volume control, but that doesn't work if I'm also playing audio from other apps at the same time.

**Comment by Ciock** [comment]
I would place the volume slider under the global play/pause button. To gain some space, I think we can remove the phrase on top that is not necessary.

To make it clear, to me the behavior should be that the global volume slider adjusts others, but doesn't set them to its value. For example:

Song A playing at 50%, and song B playing at 100%. Then I set the global volume slider at 50%, the songs relative slider doesn't change in UI, but A will play at 25% and B at 50%.


![x49kpsge91d51](https://user-images.githubusercontent.com/35781302/179344069-574c4d99-7a20-4bdd-91cb-9087988fe9d3.png)

**Comment by Ciock** [comment]
It's under review by Google, it'll be out in a couple of hours 👍
